server:
  port: 8080
  http2:
    enabled: true
  ssl:
    bundle: "secure-service"
#    enabled-protocols: "TLSv1.3"

#spring:
#  ssl:
#    bundle:
#      pem:
#        mybundle:
#          reload-on-update: true
#          keystore:
#            certificate: "file:/some/directory/application.crt"
#            private-key: "file:/some/directory/application.key"

spring:
  ssl:
    bundle:
      jks:
        secure-service:
          key:
            alias: "mycertificate"
          keystore:
            location: "classpath:keystore.p12"
            password: "mycertificate"
            type: "PKCS12"